name: publish-image

on:
  release:
    types: [published, edited, released]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: gvidelio
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish release
        if: "!github.event.release.prerelease"
        run: |
          docker buildx build \
            --cache-from gvidelio/uno:latest \
            --platform linux/arm/v7,linux/amd64 \
            --tag "gvidelio/uno:latest" \
            --tag "gvidelio/uno:${GITHUB_REF##*/}" \
            --push \
            --file ./Dockerfile .
      - name: Publish pre-release
        if: "github.event.release.prerelease"
        run: |
          docker buildx build \
            --cache-from gvidelio/uno:latest \
            --platform linux/arm/v7,linux/amd64 \
            --tag "gvidelio/uno:${GITHUB_REF##*/}" \
            --push \
            --file ./Dockerfile .